### ISSUE TITLE
arm64 building

### ISSUE THREAD

**Issue by bainss** [jenkins-x/enhancements#14]
Hi,

I'm trying to build for arm64, the documentation points to a 404.

**Comment by jstrachan** [comment]
we've started a general arm enhancement process https://github.com/jenkins-x/enhancements/issues/33 to try get jx working on ARM; so I'll close this issue for now.

Note that many many issues will be generated + changes made to lots of git repositories (as many images are required for Jenkins X) - so we've got a separate project to track all the various parts related to ARM support: https://github.com/jenkins-x/jenkins-x-arm-support so if there's an ARM related issue about a specific container/binary/image please raise an issue here: https://github.com/jenkins-x/jenkins-x-arm-support/issues
