### ISSUE TITLE
Enhance JX UI

### ISSUE THREAD

**Issue by cdbkr** [jenkins-x/enhancements#25]
JX UI looks great and it gives a high-level view of the current status of the builds, environments, projects and so on.
As user, it would be really great to be able to:
- Configure namespaces (at the moment 'jx' is hardcoded in some places and it is not possible to configure it)
- Support GHE or a configurable wat for Git Providers/Services (e.g. links/images seem to point towards Github only - so they are broken)
- Have covered edge-cases in builds' completion/status (collected builds, old ones, stuck, etc..)
- Check the Codebase for potential contributions

**Comment by jstrachan** [comment]
we've an OSS plugin for octant now: https://github.com/jenkins-x/octant-jx which hopefully has the features you need; if not we could create the necessary issues there & hack on the code to improve it?

**Comment by cdbkr** [comment]
thank you very much @jstrachan! I have just tried it and it looks great (and those features seem implemented there)! 
what about users not able to access the cluster resources directly and not able to use octant? (e.g. a developer who is taking care of a project managed by jx - or non-technical users such as Scrum Master or Product Owner)
