### ISSUE TITLE
support Tekton Catalog

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/enhancements#37]
the [tekton catalog](https://github.com/tektoncd/catalog) provides a great way to share `Task` and `Pipeline` resources across CI/CD projects for anyone using [Tekton](https://tekton.dev/). Currently its not easy to reuse Tekton catalog with Jenkins X.

It would be awesome if we could support Tekton Catalog so that:

* Jenkins X users can consume any `Task` or `Pipeline` resources easily from the catalog
* we can expose Jenkins X Pipelines to our own Jenkins X Tekton Catalog so that anyone from the Tekton ecosystem can reuse any of the Jenkins X TasksPipelines
* we figure out a nice way to share tekton resources across microservices and teams without just 'copy & paste' everywhere which soon turns into a maintenance nightmare

We maybe also want to ensure folks can reuse the ChatOps capabilities from [lighthouse](https://github.com/jenkins-x/lighthouse) when using vanilla Tekton. 

Being able to enhance the ChatOps capabilities in Jenkins X via Tekton Catalogs would be aweome too! - e.g. binding Task/Pipeline resources from a catalog to a ChatOps command on a number of repositories/branches etc

**Comment by rawlingsj** [comment]
It would also be good to review the Jenkins X use of build packs as part of this and see if we can move the reusability part of the build to tekton catalog tasks.  Then all that's left of a Jenkins X build pack is the enriching of pipelines with helm charts, pipelines and dockerfiles if needed when creating a new quickstart or importing an existing application.  It might therefore be possible to standardise on CNCF build packs and deprecate Jenkins X ones as they have often caused confusion plus use a slightly different DSL to a `jenkins-x.yml`.

We would need a migration path here which hopefully wouldn't be too hard as we could generate the tekton resources used from a build pack and move them to tekton tasks.

**Comment by jstrachan** [comment]
here's an implementation: https://jenkins-x.io/docs/v3/guides/pipeline-catalog/
