### ISSUE TITLE
Preview with Helmfile

### ISSUE THREAD

**Issue by vbehar** [jenkins-x/enhancements#38]
See #26

TL;DR
- the preview environments are based on Helm 2 and "umbrella charts" - so we can add dependencies, but it's not very flexible
- we'll need to switch to Helm 3 - related to #34
- [Helmfile](https://github.com/roboll/helmfile) is a higher-level tool build on top of Helm, which can be used to declaratively define an environment composed of multiple Helm releases. It supports both Helm 2 and Helm 3, and could be used to switch smoothly from one to the other for the preview env.

**Comment by vbehar** [comment]
FYI we've been deploying our preview envs at Dailymotion using Helmfile (and Helm 3) for a few months now, and... it's so much better ;-)

**Comment by nimajalali** [comment]
@vbehar Is the helmfile feature something that's available using off the shelf jx or are you running a fork internally?

**Comment by nimajalali** [comment]
I see now that jx v3 uses helmfile.

**Comment by jstrachan** [comment]
@vbehar i wonder how do you GC your preview environments with helmfile? Do you assume all resources are in the same namespace and remove that? 

Just wondered. If we moved to helmfile for previews it would be awesome if folks could create a Canary in the staging namespace- which should be easy via a helmfile - am just not sure how removal of previews would work

**Comment by vbehar** [comment]
@jstrachan good question. we have our own GC, which is based on the std one. It does the following
- find all preview envs
- only keep the preview envs with closed/merged PRs
- delete all helm 3 releases in the preview env namespace
- delete the environment crd
- and delete the namespace
- in case of error, it writes a comment on the github PR

it works in our case because we're using helmfile with helm3, and 1 namespace per preview env. we need to delete each helm release because some projects rely on helm hooks (pre-install and post-delete) to create/delete cloud resources (gcs buckets, pubsub topics, ...)

ideally we should use the `helmfile destroy` command, but it requires to have access to the PR's source code.

**Comment by jstrachan** [comment]
here's the first spike of helmfile based previews... https://github.com/jenkins-x/jx-preview/blob/master/README.md

we're using a `Preview` custom resource to keep track of the source code (and user/token to clone it) so we can do a real `helmfile destroy` when we destroy or garbage collect a preview. 

Its working great + is fully integrated into [Jenkins X 3.x](https://jenkins-x.io/docs/v3/) now and the BDD tests are green

would love to support [Terraform based previews](https://github.com/jenkins-x/jx-preview/issues/45) as well so we could spin up a custom cluster / cloud infrastructure used by the preview - then tear it all down afterwards

**Comment by vbehar** [comment]
that's awesome! Mainly the fact that you use `helmfile destroy`, so it's a clean deletion
